[package]
name = "ald-timesync"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ald-core = { path = "../ald-core" }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
