//! Aldivine Framework — economy service.
//!
//! Server-authoritative money. All mutations go through this service so that
//! balance validation and the audit ledger can never be bypassed by a script
//! or a client. Transfers are atomic: either both legs and the ledger entry
//! commit, or nothing changes.
//!
//! This module owns only the in-memory authoritative balances plus the ledger
//! of intent; the persistence layer (ald-database) records committed
//! transactions. Callers must hold no other locks when calling `transfer`.

use std::collections::HashMap;

use ald_core::AldivinePlayerId;

/// Account kinds the platform knows natively. Custom account names are
/// allowed for resources, but the well-known ones are typed here so that
/// typos cannot silently create a new currency.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AccountKind {
    Cash,
    Bank,
    Organization,
}

impl AccountKind {
    pub fn as_str(self) -> &'static str {
        match self {
            AccountKind::Cash => "cash",
            AccountKind::Bank => "bank",
            AccountKind::Organization => "organization",
        }
    }
}

/// An immutable record of one money movement. The source of truth for audits.
#[derive(Debug, Clone)]
pub struct Transaction {
    /// ULID of this transaction, generated by the caller (server-side).
    pub id: String,
    pub from_player: AldivinePlayerId,
    pub from_account: AccountKind,
    pub to_player: AldivinePlayerId,
    pub to_account: AccountKind,
    /// Non-negative. Zero-value transfers are rejected.
    pub amount: u64,
    /// Resource or system that requested the transfer.
    pub reason: String,
}

#[derive(Debug, thiserror::Error)]
pub enum EconomyError {
    #[error("insufficient funds: have {have}, need {need}")]
    InsufficientFunds { have: u64, need: u64 },
    #[error("amount must be greater than zero")]
    NonPositiveAmount,
    #[error("self-transfer between identical accounts is a no-op and rejected")]
    SelfTransfer,
    #[error("account {account} is overdrawn; ledger is inconsistent")]
    Inconsistent { account: String },
}

/// Authoritative economy state. Single owner (the economy service task).
#[derive(Debug, Default)]
pub struct EconomyService {
    /// (player, account kind) -> balance in cents.
    balances: HashMap<(AldivinePlayerId, AccountKind), u64>,
    /// Append-only ledger of committed transactions.
    ledger: Vec<Transaction>,
}

impl EconomyService {
    pub fn new() -> Self {
        EconomyService::default()
    }

    /// Balance of one account. Accounts spring into existence at zero.
    pub fn balance(&self, player: AldivinePlayerId, kind: AccountKind) -> u64 {
        self.balances.get(&(player, kind)).copied().unwrap_or(0)
    }

    /// Mint money into an account. Restricted to system calls (salary payouts,
    /// server console adjustments). Resources should never call this: they
    /// would inflate the economy without a matching debit.
    pub fn credit(&mut self, player: AldivinePlayerId, kind: AccountKind, amount: u64) -> Result<(), EconomyError> {
        if amount == 0 {
            return Err(EconomyError::NonPositiveAmount);
        }
        *self.balances.entry((player, kind)).or_insert(0) += amount;
        Ok(())
    }

    /// Remove money from an account. Fails if it would overdraw.
    pub fn debit(&mut self, player: AldivinePlayerId, kind: AccountKind, amount: u64) -> Result<(), EconomyError> {
        if amount == 0 {
            return Err(EconomyError::NonPositiveAmount);
        }
        let entry = self.balances.entry((player, kind)).or_insert(0);
        if *entry < amount {
            return Err(EconomyError::InsufficientFunds { have: *entry, need: amount });
        }
        *entry -= amount;
        Ok(())
    }

    /// Atomic transfer: validate -> debit -> credit -> ledger.
    /// The validation and both balance mutations happen with no await points
    /// in between, so the operation cannot be observed half-applied.
    pub fn transfer(&mut self, txn: Transaction) -> Result<(), EconomyError> {
        if txn.amount == 0 {
            return Err(EconomyError::NonPositiveAmount);
        }
        if txn.from_player == txn.to_player && txn.from_account == txn.to_account {
            return Err(EconomyError::SelfTransfer);
        }

        // Debit first; the only failure mode here is insufficient funds, and
        // it leaves balances untouched.
        self.debit(txn.from_player, txn.from_account, txn.amount)?;
        // Credit cannot fail after a successful debit (amount > 0), so the
        // pair stays atomic.
        self.credit(txn.to_player, txn.to_account, txn.amount)?;

        // Record intent after the money moved, so the ledger only ever
        // describes committed state.
        self.ledger.push(txn);
        Ok(())
    }

    /// Total money in circulation. Diagnostic for economy health in Aegis.
    pub fn money_supply(&self) -> u64 {
        self.balances.values().sum()
    }

    /// Number of committed transactions.
    pub fn txn_count(&self) -> usize {
        self.ledger.len()
    }

    /// Read-only view of the ledger (for audit export).
    pub fn ledger(&self) -> &[Transaction] {
        &self.ledger
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ulid::Ulid;

    fn pid() -> AldivinePlayerId {
        AldivinePlayerId::new()
    }

    fn txn(a: AldivinePlayerId, b: AldivinePlayerId, amt: u64) -> Transaction {
        Transaction {
            id: Ulid::new().to_string(),
            from_player: a,
            from_account: AccountKind::Cash,
            to_player: b,
            to_account: AccountKind::Cash,
            amount: amt,
            reason: "test".into(),
        }
    }

    #[test]
    fn balance_starts_zero() {
        let s = EconomyService::new();
        assert_eq!(s.balance(pid(), AccountKind::Cash), 0);
    }

    #[test]
    fn credit_and_debit() {
        let mut s = EconomyService::new();
        let p = pid();
        s.credit(p, AccountKind::Bank, 500).unwrap();
        assert_eq!(s.balance(p, AccountKind::Bank), 500);
        s.debit(p, AccountKind::Bank, 200).unwrap();
        assert_eq!(s.balance(p, AccountKind::Bank), 300);
    }

    #[test]
    fn debit_refuses_overdraft() {
        let mut s = EconomyService::new();
        let p = pid();
        let err = s.debit(p, AccountKind::Cash, 100).unwrap_err();
        assert!(matches!(err, EconomyError::InsufficientFunds { have: 0, need: 100 }));
        assert_eq!(s.balance(p, AccountKind::Cash), 0);
    }

    #[test]
    fn transfer_moves_money_and_records_ledger() {
        let mut s = EconomyService::new();
        let a = pid();
        let b = pid();
        s.credit(a, AccountKind::Cash, 1000).unwrap();

        s.transfer(txn(a, b, 400)).unwrap();
        assert_eq!(s.balance(a, AccountKind::Cash), 600);
        assert_eq!(s.balance(b, AccountKind::Cash), 400);
        assert_eq!(s.txn_count(), 1);
        assert_eq!(s.money_supply(), 1000); // conservation check
    }

    #[test]
    fn transfer_rejects_self() {
        let mut s = EconomyService::new();
        let p = pid();
        s.credit(p, AccountKind::Cash, 100).unwrap();
        assert!(matches!(s.transfer(txn(p, p, 10)), Err(EconomyError::SelfTransfer)));
        assert_eq!(s.balance(p, AccountKind::Cash), 100);
    }

    #[test]
    fn transfer_rejects_zero_and_insufficient() {
        let mut s = EconomyService::new();
        let a = pid();
        let b = pid();
        assert!(matches!(s.transfer(txn(a, b, 0)), Err(EconomyError::NonPositiveAmount)));
        s.credit(a, AccountKind::Cash, 50).unwrap();
        assert!(s.transfer(txn(a, b, 100)).is_err());
        assert_eq!(s.balance(a, AccountKind::Cash), 50);
    }
}
